### PR TITLE
Change maintainership

### PR DESCRIPTION
**Pull request by alanocallaghan**
The transfer process I believe is that I submit the new version to CRAN and you should be notified on your listed email, if you respond from that email it should be golden

If you can add me as a dev to this repo that'd be great, since probably there are links suggesting this is the primary git repo, and it's where issues are likely to land. Failing that I can just watch this repo and push stuff to my fork, doesn't make a huge amount of odds

### CODE REVIEW

**Comment by rhenkin** [comment]
Hi, just wanted to know if there are any updates on this?

**Comment by AliciaSchep** [comment]
Sorry for delay here, didn't catch this.  Merging now and will see if I can add you to this repo!

**Comment by alanocallaghan** [comment]
Super, I'll build and push to CRAN later today

**Comment by alanocallaghan** [comment]
> CRAN submissions will be offline from Jul 21, 2023 to Aug 7, 2023 (CRAN team vacation and maintenance work).

Will submit the 8th

**Pull request merged**
